services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ECommerceAPI
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: